import React, { useState } from 'react';
import { authAPI } from '../utils/api';
import './ResuHelp.css';

const ResuHelp = () => {
  const [resumeFile, setResumeFile] = useState(null);
  const [jobDescriptionFile, setJobDescriptionFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [analysisResult, setAnalysisResult] = useState(null);

  const handleResumeChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      // Check file type (PDF, DOC, DOCX, TXT)
      const allowedTypes = ['application/pdf', 'application/msword', 
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];
      if (allowedTypes.includes(file.type)) {
        setResumeFile(file);
        setError('');
      } else {
        setError('Please upload a valid file (PDF, DOC, DOCX, or TXT)');
        setResumeFile(null);
      }
    }
  };

  const handleJobDescriptionChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      const allowedTypes = ['application/pdf', 'application/msword', 
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];
      if (allowedTypes.includes(file.type)) {
        setJobDescriptionFile(file);
        setError('');
      } else {
        setError('Please upload a valid file (PDF, DOC, DOCX, or TXT)');
        setJobDescriptionFile(null);
      }
    }
  };

  const handleAnalyze = async () => {
    if (!resumeFile || !jobDescriptionFile) {
      setError('Please upload both Resume and Job Description files');
      return;
    }

    setLoading(true);
    setError('');
    setAnalysisResult(null);

    try {
      const formData = new FormData();
      formData.append('resume', resumeFile);
      formData.append('jobDescription', jobDescriptionFile);

      const response = await authAPI.analyzeResume(formData);
      setAnalysisResult(response.data);
    } catch (err) {
      const errorMessage = err.response?.data?.message || 
                          err.response?.data?.error || 
                          err.message || 
                          'Analysis failed. Please try again.';
      setError(errorMessage);
      console.error('Analysis error:', err.response?.data || err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadReport = () => {
    if (!analysisResult) return;

    // Create a downloadable report
    const reportContent = `
RESUME ANALYSIS REPORT
Generated by ResuMate
Date: ${new Date().toLocaleString()}

=================================================================
JOB FIT SCORE: ${analysisResult.jobFitScore}/100
=================================================================

${analysisResult.analysis}

RECOMMENDATIONS:
${analysisResult.recommendations}

MATCHED KEYWORDS:
${analysisResult.matchedKeywords.join(', ')}

MISSING KEYWORDS:
${analysisResult.missingKeywords.join(', ')}
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Resume_Analysis_Report_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  return (
    <div className="resuhelp-container">
      <h2>ResuHelp - AI Resume Analyzer</h2>
      <p className="resuhelp-subtitle">
        Upload your resume and job description to get an AI-powered analysis report
      </p>

      <div className="upload-section">
        <div className="upload-card">
          <label htmlFor="resume-upload" className="upload-label">
            <div className="upload-icon">📄</div>
            <div className="upload-text">
              <h3>Upload Resume</h3>
              <p>PDF, DOC, DOCX, or TXT</p>
              {resumeFile && <span className="file-name">{resumeFile.name}</span>}
            </div>
          </label>
          <input
            type="file"
            id="resume-upload"
            accept=".pdf,.doc,.docx,.txt"
            onChange={handleResumeChange}
            className="file-input"
          />
        </div>

        <div className="upload-card">
          <label htmlFor="jd-upload" className="upload-label">
            <div className="upload-icon">📋</div>
            <div className="upload-text">
              <h3>Upload Job Description</h3>
              <p>PDF, DOC, DOCX, or TXT</p>
              {jobDescriptionFile && <span className="file-name">{jobDescriptionFile.name}</span>}
            </div>
          </label>
          <input
            type="file"
            id="jd-upload"
            accept=".pdf,.doc,.docx,.txt"
            onChange={handleJobDescriptionChange}
            className="file-input"
          />
        </div>
      </div>

      {error && <div className="error-message">{error}</div>}

      <button 
        className="analyze-button" 
        onClick={handleAnalyze} 
        disabled={loading || !resumeFile || !jobDescriptionFile}
      >
        {loading ? 'Analyzing...' : 'ANALYZE'}
      </button>

      {analysisResult && (
        <div className="analysis-result">
          <div className="job-fit-score">
            <h3>Job Fit Score</h3>
            <div className="score-circle">
              <span className="score-value">{analysisResult.jobFitScore}</span>
              <span className="score-total">/100</span>
            </div>
            <p className="score-description">{analysisResult.scoreDescription}</p>
          </div>

          <div className="analysis-details">
            <div className="detail-section">
              <h4>Analysis</h4>
              <p>{analysisResult.analysis}</p>
            </div>

            <div className="detail-section">
              <h4>Recommendations</h4>
              <ul>
                {analysisResult.recommendations.split('\n').map((rec, index) => 
                  rec.trim() && <li key={index}>{rec.trim()}</li>
                )}
              </ul>
            </div>

            <div className="keywords-section">
              <div className="keywords-box matched">
                <h4>Matched Keywords</h4>
                <div className="keywords-list">
                  {analysisResult.matchedKeywords.map((keyword, index) => (
                    <span key={index} className="keyword-tag matched-tag">{keyword}</span>
                  ))}
                </div>
              </div>

              <div className="keywords-box missing">
                <h4>Missing Keywords</h4>
                <div className="keywords-list">
                  {analysisResult.missingKeywords.map((keyword, index) => (
                    <span key={index} className="keyword-tag missing-tag">{keyword}</span>
                  ))}
                </div>
              </div>
            </div>

            <button className="download-button" onClick={handleDownloadReport}>
              📥 Download Analysis Report
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default ResuHelp;

