import React, { useState } from 'react';
import { authAPI } from '../utils/api';
import './ResuHelp.css';

const ResuHelp = () => {
  const [resumeFile, setResumeFile] = useState(null);
  const [jobDescriptionFile, setJobDescriptionFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [analysisResult, setAnalysisResult] = useState(null);
  const [generatingResume, setGeneratingResume] = useState(false);
  const [atsResumeText, setAtsResumeText] = useState('');

  const handleResumeChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      // Check file type (PDF, DOC, DOCX, TXT)
      const allowedTypes = ['application/pdf', 'application/msword', 
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];
      if (allowedTypes.includes(file.type)) {
        setResumeFile(file);
        setError('');
      } else {
        setError('Please upload a valid file (PDF, DOC, DOCX, or TXT)');
        setResumeFile(null);
      }
    }
  };

  const handleJobDescriptionChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      const allowedTypes = ['application/pdf', 'application/msword', 
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];
      if (allowedTypes.includes(file.type)) {
        setJobDescriptionFile(file);
        setError('');
      } else {
        setError('Please upload a valid file (PDF, DOC, DOCX, or TXT)');
        setJobDescriptionFile(null);
      }
    }
  };

  const handleAnalyze = async () => {
    if (!resumeFile || !jobDescriptionFile) {
      setError('Please upload both Resume and Job Description files');
      return;
    }

    setLoading(true);
    setError('');
    setAnalysisResult(null);

    try {
      const formData = new FormData();
      formData.append('resume', resumeFile);
      formData.append('jobDescription', jobDescriptionFile);

      const response = await authAPI.analyzeResume(formData);
      setAnalysisResult(response.data);
    } catch (err) {
      const errorMessage = err.response?.data?.message || 
                          err.response?.data?.error || 
                          err.message || 
                          'Analysis failed. Please try again.';
      setError(errorMessage);
      console.error('Analysis error:', err.response?.data || err);
    } finally {
      setLoading(false);
    }
  };

  const getCleanAnalysis = (analysis) => {
    if (!analysis) return '';
    let text = typeof analysis === 'string' ? analysis : String(analysis);

    text = text.trim();

    // Strip markdown code fences if present
    if (text.startsWith('```')) {
      text = text.replace(/^```[a-zA-Z0-9]*\s*/, '');
      if (text.endsWith('```')) {
        text = text.slice(0, -3).trim();
      }
    }

    // Try to parse JSON and extract the "analysis" field
    if (text.startsWith('{')) {
      try {
        const parsed = JSON.parse(text);
        if (parsed && typeof parsed.analysis === 'string') {
          return parsed.analysis.trim();
        }
      } catch (e) {
        // Not valid JSON, fall through to plain text
      }
    }

    return text;
  };

  const getRecommendationLines = (result) => {
    if (!result || !result.recommendations) return [];
    const rec = result.recommendations;
    if (Array.isArray(rec)) {
      return rec.map((r) => String(r));
    }
    if (typeof rec === 'string') {
      return rec.split('\n');
    }
    return [String(rec)];
  };

  const handleDownloadReport = () => {
    if (!analysisResult) return;

    // Create a downloadable report
    const reportContent = `
RESUME ANALYSIS REPORT
Generated by ResuMate
Date: ${new Date().toLocaleString()}

=================================================================
JOB FIT SCORE: ${analysisResult.jobFitScore}/100
=================================================================

${analysisResult.analysis}

RECOMMENDATIONS:
${analysisResult.recommendations}

MATCHED KEYWORDS:
${analysisResult.matchedKeywords.join(', ')}

MISSING KEYWORDS:
${analysisResult.missingKeywords.join(', ')}
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Resume_Analysis_Report_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  const handleGenerateAtsResume = async () => {
    if (!analysisResult) return;

    setError('');
    setGeneratingResume(true);

    try {
      // Fetch the user's profile
      const profileResponse = await authAPI.getProfile();
      const profile = profileResponse.data?.profile;

      if (!profile) {
        throw new Error('Profile not found. Please complete your profile first.');
      }

      const response = await authAPI.generateAtsResume({
        profile,
        analysisResult,
      });

      const resumeText = response.data?.resumeText;

      if (!resumeText) {
        throw new Error('Failed to generate ATS-friendly resume. No content returned.');
      }

      // Store the generated resume text for preview and later download
      setAtsResumeText(resumeText);
    } catch (err) {
      const errorMessage =
        err.response?.data?.message ||
        err.response?.data?.error ||
        err.message ||
        'Failed to generate ATS-friendly resume. Please try again.';
      setError(errorMessage);
      console.error('ATS resume generation error:', err.response?.data || err);
    } finally {
      setGeneratingResume(false);
    }
  };

  const handleDownloadAtsResume = () => {
    if (!atsResumeText) return;

    const blob = new Blob([atsResumeText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ATS_Friendly_Resume_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  return (
    <div className="resuhelp-container">
      <h2>ResuHelp - AI Resume Analyzer</h2>
      <p className="resuhelp-subtitle">
        Upload your resume and job description to get an AI-powered analysis report
      </p>

      <div className="upload-section">
        <div className="upload-card">
          <label htmlFor="resume-upload" className="upload-label">
            <div className="upload-icon">📄</div>
            <div className="upload-text">
              <h3>Upload Resume</h3>
              <p>PDF, DOC, DOCX, or TXT</p>
              {resumeFile && <span className="file-name">{resumeFile.name}</span>}
            </div>
          </label>
          <input
            type="file"
            id="resume-upload"
            accept=".pdf,.doc,.docx,.txt"
            onChange={handleResumeChange}
            className="file-input"
          />
        </div>

        <div className="upload-card">
          <label htmlFor="jd-upload" className="upload-label">
            <div className="upload-icon">📋</div>
            <div className="upload-text">
              <h3>Upload Job Description</h3>
              <p>PDF, DOC, DOCX, or TXT</p>
              {jobDescriptionFile && <span className="file-name">{jobDescriptionFile.name}</span>}
            </div>
          </label>
          <input
            type="file"
            id="jd-upload"
            accept=".pdf,.doc,.docx,.txt"
            onChange={handleJobDescriptionChange}
            className="file-input"
          />
        </div>
      </div>

      {error && <div className="error-message">{error}</div>}

      <button 
        className="analyze-button" 
        onClick={handleAnalyze} 
        disabled={loading || !resumeFile || !jobDescriptionFile}
      >
        {loading ? 'Analyzing...' : 'ANALYZE'}
      </button>

      {analysisResult && (
        <div className="analysis-result">
          <div className="job-fit-score">
            <h3>Job Fit Score</h3>
            <div className="score-circle">
              <span className="score-value">{analysisResult.jobFitScore}</span>
              <span className="score-total">/100</span>
            </div>
            <p className="score-description">{analysisResult.scoreDescription}</p>
          </div>

          <div className="analysis-details">
            <div className="detail-section">
              <h4>Analysis</h4>
              <p>{getCleanAnalysis(analysisResult.analysis)}</p>
            </div>

            <div className="detail-section">
              <h4>Recommendations</h4>
              <ul>
                {getRecommendationLines(analysisResult).map((rec, index) => {
                  const trimmed = rec.trim();
                  return trimmed ? <li key={index}>{trimmed}</li> : null;
                })}
              </ul>
            </div>

            <div className="keywords-section">
              <div className="keywords-box matched">
                <h4>Matched Keywords</h4>
                <div className="keywords-list">
                  {(analysisResult.matchedKeywords || []).map((keyword, index) => (
                    <span key={index} className="keyword-tag matched-tag">{keyword}</span>
                  ))}
                </div>
              </div>

              <div className="keywords-box missing">
                <h4>Missing Keywords</h4>
                <div className="keywords-list">
                  {(analysisResult.missingKeywords || []).map((keyword, index) => (
                    <span key={index} className="keyword-tag missing-tag">{keyword}</span>
                  ))}
                </div>
              </div>
            </div>

            <button className="download-button" onClick={handleDownloadReport}>
              📥 Download Analysis Report
            </button>

            <button
              className="download-button"
              style={{ marginTop: '10px', background: 'linear-gradient(135deg, #28a745 0%, #218838 100%)' }}
              onClick={handleGenerateAtsResume}
              disabled={generatingResume}
            >
              {generatingResume ? 'Generating ATS-Friendly Resume...' : '✨ Generate ATS-Friendly Resume'}
            </button>

            {atsResumeText && (
              <div className="ats-resume-preview">
                <h4>ATS-Friendly Resume Preview</h4>
                <div className="ats-resume-box">
                  <pre>{atsResumeText}</pre>
                </div>
                <button
                  className="download-button"
                  style={{ marginTop: '10px' }}
                  onClick={handleDownloadAtsResume}
                >
                  ⬇️ Download ATS-Friendly Resume
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default ResuHelp;

