import { useState } from 'react';
import { authAPI } from '../utils/api';
import './ResuHelp.css';

const ResuHelp = () => {
  const [resumeFile, setResumeFile] = useState(null);
  const [jobDescriptionFile, setJobDescriptionFile] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [analysisResult, setAnalysisResult] = useState(null);
  const [generatingResume, setGeneratingResume] = useState(false);
  const [atsResumeText, setAtsResumeText] = useState('');

  const handleResumeChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      // Check file type (PDF, DOC, DOCX, TXT)
      const allowedTypes = ['application/pdf', 'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];
      if (allowedTypes.includes(file.type)) {
        setResumeFile(file);
        setError('');
      } else {
        setError('Please upload a valid file (PDF, DOC, DOCX, or TXT)');
        setResumeFile(null);
      }
    }
  };

  const handleJobDescriptionChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      const allowedTypes = ['application/pdf', 'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain'];
      if (allowedTypes.includes(file.type)) {
        setJobDescriptionFile(file);
        setError('');
      } else {
        setError('Please upload a valid file (PDF, DOC, DOCX, or TXT)');
        setJobDescriptionFile(null);
      }
    }
  };

  const handleAnalyze = async () => {
    if (!resumeFile || !jobDescriptionFile) {
      setError('Please upload both Resume and Job Description files');
      return;
    }

    setLoading(true);
    setError('');
    setAnalysisResult(null);

    try {
      const formData = new FormData();
      formData.append('resume', resumeFile);
      formData.append('jobDescription', jobDescriptionFile);

      const response = await authAPI.analyzeResume(formData);
      setAnalysisResult(response.data);
    } catch (err) {
      const errorMessage = err.response?.data?.message ||
        err.response?.data?.error ||
        err.message ||
        'Analysis failed. Please try again.';
      setError(errorMessage);
      console.error('Analysis error:', err.response?.data || err);
    } finally {
      setLoading(false);
    }
  };

  const getCleanAnalysis = (analysis) => {
    if (!analysis) return '';
    let text = typeof analysis === 'string' ? analysis : JSON.stringify(analysis, null, 2);

    text = text.trim();

    // Strip markdown code fences if present
    text = text.replace(/```json/gi, '').replace(/```/g, '').trim();

    // Try to parse JSON and extract the "analysis" field
    try {
      const jsonStart = text.indexOf('{');
      const jsonEnd = text.lastIndexOf('}');
      if (jsonStart !== -1 && jsonEnd !== -1 && jsonEnd > jsonStart) {
        const jsonStr = text.substring(jsonStart, jsonEnd + 1);
        const parsed = JSON.parse(jsonStr);
        if (parsed && typeof parsed.analysis === 'string') {
          text = parsed.analysis;
        } else if (parsed && typeof parsed.message === 'string') {
          text = parsed.message;
        } else {
          // Flatten simple key-values for better readability if it's just a raw object
          text = Object.entries(parsed)
            .map(([key, val]) => `${key.toUpperCase()}:\n${typeof val === 'string' ? val : JSON.stringify(val)}`)
            .join('\n\n');
        }
      }
    } catch (e) {
      // If parsing fails, try regex to extract the "analysis" field as a fallback
      const analysisMatch = text.match(/"analysis"\s*:\s*"((?:[^"\\]|\\.)*)"/i);
      if (analysisMatch && analysisMatch[1]) {
        text = analysisMatch[1];
      }
    }

    // Unescape common JSON string escapes just in case
    return text.replace(/\\n/g, '\n').replace(/\\"/g, '"').trim();
  };

  const getRecommendationLines = (result) => {
    if (!result || !result.recommendations) return [];
    const rec = result.recommendations;
    if (Array.isArray(rec)) {
      return rec.map((r) => String(r));
    }
    if (typeof rec === 'string') {
      return rec.split('\n');
    }
    return [String(rec)];
  };

  const handleDownloadReport = () => {
    if (!analysisResult) return;

    // Create a downloadable report
    const reportContent = `
RESUME ANALYSIS REPORT
Generated by ResuMate
Date: ${new Date().toLocaleString()}

=================================================================
JOB FIT SCORE: ${analysisResult.jobFitScore}/100
=================================================================

${analysisResult.analysis}

RECOMMENDATIONS:
${analysisResult.recommendations}

MATCHED KEYWORDS:
${analysisResult.matchedKeywords.join(', ')}

MISSING KEYWORDS:
${analysisResult.missingKeywords.join(', ')}
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Resume_Analysis_Report_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  const handleGenerateAtsResume = async () => {
    if (!analysisResult) return;

    setError('');
    setGeneratingResume(true);

    try {
      // Fetch the user's profile
      const profileResponse = await authAPI.getProfile();
      const profile = profileResponse.data?.profile;

      if (!profile) {
        throw new Error('Profile not found. Please complete your profile first.');
      }

      const response = await authAPI.generateAtsResume({
        profile,
        analysisResult,
      });

      const resumeText = response.data?.resumeText;

      if (!resumeText) {
        throw new Error('Failed to generate ATS-friendly resume. No content returned.');
      }

      // Store the generated resume text for preview and later download
      setAtsResumeText(resumeText);
    } catch (err) {
      const errorMessage =
        err.response?.data?.message ||
        err.response?.data?.error ||
        err.message ||
        'Failed to generate ATS-friendly resume. Please try again.';
      setError(errorMessage);
      console.error('ATS resume generation error:', err.response?.data || err);
    } finally {
      setGeneratingResume(false);
    }
  };

  const handleDownloadAtsResume = () => {
    if (!atsResumeText) return;

    const blob = new Blob([atsResumeText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ATS_Friendly_Resume_${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  return (
    <div className="resuhelp-container">
      <div className="resuhelp-header">
        <h2>ResuMate AI Analyzer</h2>
        <p className="resuhelp-subtitle">
          Intelligent resume parsing and ATS gap-analysis.
        </p>
      </div>

      <div className={`dashboard-layout ${analysisResult ? 'has-results' : ''}`}>

        {/* Sidebar for Inputs */}
        <div className="dashboard-sidebar">
          <div className="upload-group">
            <div className={`upload-card ${resumeFile ? 'has-file' : ''}`}>
              <input
                type="file"
                accept=".pdf,.doc,.docx,.txt"
                onChange={handleResumeChange}
                className="file-input"
              />
              <div className="upload-icon">📄</div>
              <div className="upload-label">
                <h3>Resume Document</h3>
                <p>Click or drag file here</p>
                {resumeFile && <span className="file-name">{resumeFile.name}</span>}
              </div>
            </div>

            <div className={`upload-card ${jobDescriptionFile ? 'has-file' : ''}`}>
              <input
                type="file"
                accept=".pdf,.doc,.docx,.txt"
                onChange={handleJobDescriptionChange}
                className="file-input"
              />
              <div className="upload-icon">📋</div>
              <div className="upload-label">
                <h3>Job Description</h3>
                <p>Click or drag file here</p>
                {jobDescriptionFile && <span className="file-name">{jobDescriptionFile.name}</span>}
              </div>
            </div>
          </div>

          <button
            className="analyze-btn"
            onClick={handleAnalyze}
            disabled={loading || !resumeFile || !jobDescriptionFile}
          >
            {loading ? 'Processing Analysis...' : analysisResult ? 'Re-Analyze' : 'Run Analysis'}
          </button>

          {error && <div className="error-message" style={{ marginTop: '20px' }}>{error}</div>}
        </div>

        {/* Main Content for Results */}
        {analysisResult && (
          <div className="dashboard-main">
            <div className="analysis-dashboard">

              <div className="stats-row">
                <div className="stat-card">
                  <h3>Match Score</h3>
                  <div className="score-circle">
                    <span className="score-value">{analysisResult.jobFitScore}</span>
                    <span className="score-total">/100</span>
                  </div>
                  <p className="score-desc">{analysisResult.scoreDescription || 'Based on keyword frequency and relevance'}</p>
                </div>

                <div className="content-card">
                  <h4>🧠 AI Analysis</h4>
                  <p className="analysis-text">{getCleanAnalysis(analysisResult.analysis)}</p>
                </div>
              </div>

              <div className="content-card">
                <h4>🎯 Key Recommendations</h4>
                <ul className="rec-list">
                  {getRecommendationLines(analysisResult).map((rec, index) => {
                    const trimmed = rec.trim();
                    return trimmed ? <li key={index}>{trimmed}</li> : null;
                  })}
                </ul>
              </div>

              <div className="content-card">
                <h4>📊 Keyword Tracking</h4>
                <div className="keywords-grid">
                  <div className="keyword-box">
                    <h5>Matched Skills</h5>
                    <div className="tags-container">
                      {(analysisResult.matchedKeywords || []).map((kw, i) => (
                        <span key={i} className="tag matched">{kw}</span>
                      ))}
                      {(!analysisResult.matchedKeywords || analysisResult.matchedKeywords.length === 0) && (
                        <span className="tag">None</span>
                      )}
                    </div>
                  </div>

                  <div className="keyword-box">
                    <h5>Missing Skills</h5>
                    <div className="tags-container">
                      {(analysisResult.missingKeywords || []).map((kw, i) => (
                        <span key={i} className="tag missing">{kw}</span>
                      ))}
                      {(!analysisResult.missingKeywords || analysisResult.missingKeywords.length === 0) && (
                        <span className="tag">None</span>
                      )}
                    </div>
                  </div>
                </div>
              </div>

              <div className="action-center">
                <button className="action-btn download" onClick={handleDownloadReport}>
                  📥 Export PDF Report
                </button>
                <button
                  className="action-btn generate"
                  onClick={handleGenerateAtsResume}
                  disabled={generatingResume}
                >
                  {generatingResume ? '⏳ Synthesizing ATS Resume...' : '✨ Generate ATS Resume'}
                </button>
              </div>

              {atsResumeText && (
                <div className="ats-preview">
                  <h4>ATS-Optimized Resume</h4>
                  <div className="ats-content">
                    {atsResumeText}
                  </div>
                  <button
                    className="action-btn download"
                    style={{ marginTop: '20px', width: '100%' }}
                    onClick={handleDownloadAtsResume}
                  >
                    ⬇️ Download ATS Export
                  </button>
                </div>
              )}

            </div>
          </div>
        )}

      </div>
    </div>
  );
};

export default ResuHelp;

